# Generated by Django 4.2.20 on 2025-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_vaga_emprego_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga_emprego',
            name='dt_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dt. Atualização'),
        ),
    ]
