# Generated by Django 4.2.20 on 2025-09-16 15:07

from django.db import migrations, models
import django.db.models.deletion
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0010_vaga_emprego_dt_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('chave_de_acesso', models.CharField(editable=False, max_length=64, unique=True)),
                ('nome_do_responsavel_pela_divulgacao_da_vaga', models.CharField(max_length=150, verbose_name='Nome do responsável pela divulgação da vaga')),
                ('cpf_do_responsavel', models.CharField(max_length=14, unique=True, validators=[vagas.validations.validate_CPF], verbose_name='CPF do responsável')),
                ('contato_do_responsavel', models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Contato do responsável')),
                ('nome_da_empresa', models.CharField(max_length=150, verbose_name='Nome da empresa')),
                ('endereco_da_empresa', models.CharField(blank=True, max_length=100, verbose_name='Endereço da empresa')),
                ('cnpj_da_empresa', models.CharField(max_length=14, unique=True, validators=[vagas.validations.validate_CNPJ], verbose_name='CNPJ da empresa')),
                ('telefone_da_empresa', models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone da empresa')),
                ('segmento_da_empresa', models.CharField(blank=True, max_length=100, verbose_name='Segmento da empresa')),
                ('whatsapp_da_empresa', models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Whatsapp da empresa')),
                ('quantidade_de_vagas', models.IntegerField(verbose_name='Quantidade de vagas')),
                ('cargo_ofertado', models.CharField(max_length=100, verbose_name='Cargo ofertado')),
                ('tipo_de_vaga', models.CharField(choices=[('NML', 'Padrão'), ('JAP', 'Jovem aprendiz'), ('PED', 'Pessoa com deficiência'), ('EST', 'Estágio')], default='NML', max_length=3)),
                ('regime', models.CharField(blank=True, default='', max_length=100)),
                ('faixa_salarial', models.CharField(choices=[('ACB', 'À combinar'), ('MIN', 'Mínimo'), ('VALOR', 'Entrar com valor')], default='ACB', max_length=6, verbose_name='Faixa salarial')),
                ('valor_salario', models.CharField(blank=True, default='', max_length=50, verbose_name='Valor do salário')),
                ('vale_transporte', models.BooleanField(default=False, verbose_name='Vale transporte')),
                ('vale_alimentacao', models.BooleanField(default=False, verbose_name='Vale alimentação')),
                ('outros_beneficios', models.TextField(blank=True, default='', verbose_name='Outros benefícios')),
                ('carga_horaria', models.CharField(choices=[('40', '40 horas semanais'), ('44', '44 horas semanais'), ('OUT', 'Outra escala')], default='40', max_length=3, verbose_name='Carga horária')),
                ('outra_carga_horaria', models.CharField(blank=True, default='', max_length=50, verbose_name='Informe a carga horária')),
                ('experiencia', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Des', 'Desejável')], max_length=3, verbose_name='Experiência')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Descreva as demais competências e outras observações que forem pertinentes à vaga')),
                ('enviar_curriculo_para_email', models.BooleanField(default=False, verbose_name='Enviar currículos para o email da empresa')),
                ('email_para_envio', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email p/ envio dos currículos')),
                ('levar_curriculo_direto_ao_local', models.BooleanField(default=False, verbose_name='Levar currículo direto ao local da vaga')),
                ('endereco_para_levar_curriculo', models.CharField(blank=True, max_length=100, verbose_name='Endereço para levar currículo')),
                ('via_telefone_ou_whatsapp', models.BooleanField(default=False, verbose_name='Via telefone ou whatsapp')),
                ('telefone_ou_whatsapp', models.CharField(blank=True, max_length=11, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone ou whatsapp')),
                ('outra_forma_de_contato', models.BooleanField(default=False, verbose_name='Outra forma de contato')),
                ('outra_forma_de_contato_descricao', models.CharField(blank=True, max_length=100, verbose_name='Descreva a outra forma de contato')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('status_requisicao', models.CharField(choices=[('AG', 'Aguardando'), ('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada')], default='AG', max_length=2, verbose_name='Status da requisição')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.escolaridade')),
            ],
            options={
                'verbose_name': 'Requisição de Vaga',
                'verbose_name_plural': 'Requisições de Vagas',
                'ordering': ['-dt_inclusao'],
            },
        ),
    ]
