# Generated by Django 4.2.20 on 2025-09-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0011_requisicaovaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaovaga',
            name='email_da_empresa',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email da empresa'),
        ),
    ]
