# Generated by Django 4.2.20 on 2025-09-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0012_requisicaovaga_email_da_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaovaga',
            name='auth_hash_temp',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
