# Generated by Django 4.2.20 on 2025-09-16 17:23

from django.db import migrations, models
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0013_requisicaovaga_auth_hash_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaovaga',
            name='contato_do_responsavel',
            field=models.CharField(blank=True, max_length=15, validators=[vagas.validations.validate_TELEFONE], verbose_name='Contato do responsável'),
        ),
        migrations.AlterField(
            model_name='requisicaovaga',
            name='telefone_da_empresa',
            field=models.CharField(blank=True, max_length=15, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone da empresa'),
        ),
        migrations.AlterField(
            model_name='requisicaovaga',
            name='telefone_ou_whatsapp',
            field=models.CharField(blank=True, max_length=15, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone ou whatsapp'),
        ),
        migrations.AlterField(
            model_name='requisicaovaga',
            name='whatsapp_da_empresa',
            field=models.CharField(blank=True, max_length=15, validators=[vagas.validations.validate_TELEFONE], verbose_name='Whatsapp da empresa'),
        ),
    ]
