# Generated by Django 4.2.20 on 2025-09-16 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0014_alter_requisicaovaga_contato_do_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaovaga',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Dt. Atualização'),
        ),
        migrations.AddField(
            model_name='requisicaovaga',
            name='observacao_interna',
            field=models.TextField(blank=True, null=True, verbose_name='Observação interna'),
        ),
        migrations.CreateModel(
            name='HistoricoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CR', 'Criação'), ('ST', 'Mudança de Status'), ('OB', 'Observação'), ('ED', 'Edição')], max_length=2, verbose_name='Ação')),
                ('status_anterior', models.CharField(blank=True, choices=[('AG', 'Aguardando'), ('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada')], max_length=2, null=True)),
                ('status_novo', models.CharField(blank=True, choices=[('AG', 'Aguardando'), ('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada')], max_length=2, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='vagas.requisicaovaga')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Requisição',
                'verbose_name_plural': 'Históricos de Requisições',
                'ordering': ['-dt_criacao'],
            },
        ),
    ]
