# Generated by Django 4.2.20 on 2025-09-16 18:13

from django.db import migrations, models
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0015_requisicaovaga_dt_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaovaga',
            name='cnpj_da_empresa',
            field=models.CharField(max_length=14, validators=[vagas.validations.validate_CNPJ], verbose_name='CNPJ da empresa'),
        ),
        migrations.AlterField(
            model_name='requisicaovaga',
            name='cpf_do_responsavel',
            field=models.CharField(max_length=14, validators=[vagas.validations.validate_CPF], verbose_name='CPF do responsável'),
        ),
    ]
