# Generated by Django 4.2.20 on 2025-09-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0016_alter_requisicaovaga_cnpj_da_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga_emprego',
            name='requisicao_vaga',
            field=models.ForeignKey(blank=True, help_text='Requisição que originou esta vaga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.requisicaovaga', verbose_name='Requisição de Vaga'),
        ),
    ]
