# Generated by Django 4.2.20 on 2025-09-16 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0017_vaga_emprego_requisicao_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoSelecionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do candidato')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF do candidato')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('o', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('status_selecao', models.CharField(choices=[('PE', 'Pendente'), ('AP', 'Aprovado'), ('RE', 'Rejeitado'), ('CO', 'Contratado')], default='PE', max_length=2, verbose_name='Status da Seleção')),
                ('observacao_selecao', models.TextField(blank=True, null=True, verbose_name='Observação da Seleção')),
                ('dt_selecao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Seleção')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('escolaridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.escolaridade')),
                ('requisicao_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos_selecionados', to='vagas.requisicaovaga')),
                ('usuario_selecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Selecionou')),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos_selecionados', to='vagas.vaga_emprego')),
            ],
            options={
                'verbose_name': 'Candidato Selecionado',
                'verbose_name_plural': 'Candidatos Selecionados',
                'ordering': ['-dt_selecao'],
                'unique_together': {('requisicao_vaga', 'cpf')},
            },
        ),
    ]
