# Generated by Django 4.2.20 on 2025-09-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0018_candidatoselecionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicorequisicao',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('AG', 'Aguardando'), ('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada'), ('AE', 'Aguardando Encerramento'), ('EN', 'Encerrada')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicorequisicao',
            name='status_novo',
            field=models.CharField(blank=True, choices=[('AG', 'Aguardando'), ('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada'), ('AE', 'Aguardando Encerramento'), ('EN', 'Encerrada')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='requisicaovaga',
            name='status_requisicao',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada'), ('AE', 'Aguardando Encerramento'), ('EN', 'Encerrada')], default='AG', max_length=2, verbose_name='Status da requisição'),
        ),
    ]
