# Generated by Django 4.2.20 on 2025-09-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0019_alter_historicorequisicao_status_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaovaga',
            name='chave_de_acesso',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
