# Generated by Django 4.2.20 on 2025-09-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0020_alter_requisicaovaga_chave_de_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo na empresa')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='vagas.empresa', verbose_name='Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Responsável da Empresa',
                'verbose_name_plural': 'Responsáveis das Empresas',
                'ordering': ['user__first_name'],
                'unique_together': {('empresa', 'user')},
            },
        ),
    ]
