# Generated by Django 4.2.20 on 2025-09-18 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0021_responsavelempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavelempresa',
            options={'ordering': ['nome'], 'verbose_name': 'Responsável da Empresa', 'verbose_name_plural': 'Responsáveis das Empresas'},
        ),
        migrations.AlterUniqueTogether(
            name='responsavelempresa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='responsavelempresa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='responsavelempresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='responsavelempresa',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='responsavelempresa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='responsavelempresa',
            unique_together={('empresa', 'cpf')},
        ),
    ]
