# Generated by Django 4.2.20 on 2025-09-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vagas.validations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0023_popular_campos_responsavel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsavelempresa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='responsavelempresa',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo na empresa'),
        ),
        migrations.AlterField(
            model_name='responsavelempresa',
            name='cpf',
            field=models.CharField(max_length=14, null=True, validators=[vagas.validations.validate_CPF], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='responsavelempresa',
            name='telefone',
            field=models.CharField(max_length=15, validators=[vagas.validations.validate_TELEFONE], verbose_name='Telefone para contato'),
        ),
        migrations.AlterField(
            model_name='responsavelempresa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
