# Generated by Django 4.2.20 on 2025-09-23 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0024_alter_responsavelempresa_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavelempresa',
            name='nivel',
            field=models.CharField(choices=[('RESP', 'Responsável Principal'), ('AUX', 'Auxiliar')], default='RESP', max_length=4, verbose_name='Nível de acesso'),
        ),
        migrations.AddField(
            model_name='vaga_emprego',
            name='dt_solicitacao_desativacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de solicitação de desativação'),
        ),
        migrations.AddField(
            model_name='vaga_emprego',
            name='motivo_solicitacao_desativacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da solicitação de desativação'),
        ),
        migrations.AddField(
            model_name='vaga_emprego',
            name='observacoes_solicitacao_desativacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da solicitação de desativação'),
        ),
        migrations.AddField(
            model_name='vaga_emprego',
            name='solicitacao_desativacao',
            field=models.BooleanField(default=False, verbose_name='Solicitação de desativação'),
        ),
        migrations.AddField(
            model_name='vaga_emprego',
            name='usuario_solicitacao_desativacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_desativacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que solicitou a desativação'),
        ),
    ]
