# Generated by Django 4.2.20 on 2025-10-08 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0025_responsavelempresa_nivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDesativacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('vaga_preenchida', 'Vaga já preenchida'), ('sem_candidatos', 'Não recebemos candidatos adequados'), ('vaga_suspensa', 'Vaga temporariamente suspensa'), ('vaga_cancelada', 'Vaga cancelada'), ('outro', 'Outro motivo')], max_length=20, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10, verbose_name='Status')),
                ('dt_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('observacoes_admin', models.TextField(blank=True, verbose_name='Observações do Administrador')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('empresa_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_desativacao', to='vagas.responsavelempresa')),
                ('formulario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_desativacao', to='vagas.requisicaovaga')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_processadas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_desativacao', to='vagas.vaga_emprego')),
            ],
            options={
                'verbose_name': 'Solicitação de Desativação',
                'verbose_name_plural': 'Solicitações de Desativação',
                'ordering': ['-dt_criacao'],
            },
        ),
    ]
