# Generated by Django 4.2.20 on 2025-10-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0026_solicitacaodesativacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaodesativacao',
            name='empresa_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_desativacao', to='vagas.responsavelempresa'),
        ),
    ]
