# Generated by Django 4.2.20 on 2025-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0027_alter_solicitacaodesativacao_empresa_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaodesativacao',
            options={'ordering': ['dt_atualizacao'], 'verbose_name': 'Solicitação de Desativação', 'verbose_name_plural': 'Solicitações de Desativação'},
        ),
        migrations.AlterField(
            model_name='solicitacaodesativacao',
            name='motivo',
            field=models.CharField(choices=[('vaga_preenchida', 'Vaga já preenchida'), ('sem_candidatos', 'Não recebemos candidatos adequados'), ('vaga_suspensa', 'Vaga temporariamente suspensa'), ('vaga_cancelada', 'Vaga cancelada'), ('outro', 'Outro motivo')], max_length=150, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='solicitacaodesativacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Vaga Encerrada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10, verbose_name='Status'),
        ),
    ]
