# Generated by Django 4.2.24 on 2025-10-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0028_alter_solicitacaodesativacao_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Vaga_Emprego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('0', 'Criação da vaga'), ('+', 'Aumento'), ('-', 'Diminuição')], max_length=1, verbose_name='Tipo de alteração')),
                ('quantidadeVagas', models.IntegerField(verbose_name='Quantidade de vagas')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Alteração')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga_emprego')),
            ],
        ),
    ]
