# Generated by Django 4.2.24 on 2025-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0029_historico_vaga_emprego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga_emprego',
            name='quantidadeVagas',
            field=models.IntegerField(blank=True, verbose_name='Quantidade de vagas'),
        ),
    ]
